version: '3'

services:
  etcd:
    image: bitnami/etcd:3.5.9
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_ENABLED_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      # 将 'etcd' 改为宿主机地址
      - ETCD_ADVERTISE_CLIENT_URLS=http://172.17.235.117:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./components/etcd/data:/bitnami/etcd/data
      - ./components/etcd/logs:/bitnami/etcd/logs
    networks:
      im-zero:

  redis:
    image: redis:alpine
    ports:
      - "16379:6379"
    container_name: redis
    volumes:
      - ./components/redis/data:/data
      - ./components/redis/etc/redis.conf:/usr/local/redis/etc/redis.conf
    environment:
      TZ: Asia/Shanghai
    restart: always
    networks:
      im-zero:

  mysql:
    image: mysql:5.7
    ports:
      - "13306:3306"
    container_name: im-mysql
    volumes:
      - ./components/mysql/data:/var/lib/mysql
      - ./components/mysql/my.cnf:/etc/mysql/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    restart: always
    networks:
      im-zero:

networks:
  im-zero:
    driver: bridge